'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.SubscriptionTools

    Partial Public Class EditReceipt

        '''<summary>
        '''rptBreadCrumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptBreadCrumbs As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlAddReceipt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddReceipt As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dshReceipt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshReceipt As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblReceipt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblReceipt As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblReceiptSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReceiptSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUserName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUserName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valUserName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valUserNameExists control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valUserNameExists As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''plSelectPlan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSelectPlan As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpSelectPlan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpSelectPlan As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plAddToRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddToRole As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAddToRole control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAddToRole As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshAdvanced control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshAdvanced As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblAddReceiptAdvanced control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAddReceiptAdvanced As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plStartDate2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStartDate2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdStartDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valStartDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''plProcessor2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plProcessor2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtProcessor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProcessor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plTransactionID2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTransactionID2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTransactionID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTransactionID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDetail As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dshReceiptDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshReceiptDetail As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblReceiptDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblReceiptDetail As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblReceiptDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReceiptDetail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plUserName2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUserName2 As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUserName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plPlan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPlan As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblPlan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPlan As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plCreateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCreateDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblCreateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreateDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStartDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEndDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEndDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plProcessor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plProcessor As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblProcessor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProcessor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plTransactionID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTransactionID As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lnkTransactionID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkTransactionID As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblTransactionID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTransactionID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plServiceFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plServiceFee As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblServiceFee control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblServiceFee As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
