'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.312
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace Ventrian.SubscriptionTools

    '''<summary>
    '''SignupPlan class.
    '''</summary>
    '''<remarks>
    '''Auto-generated class.
    '''</remarks>
    Partial Public Class SignupPlan

        '''<summary>
        '''pnlPlans control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPlans As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''litContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litContent As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSelectPlan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectPlan As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valPlans control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPlans As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valPlansSelected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPlansSelected As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''lstPlans control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstPlans As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''lstPlansMultiple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstPlansMultiple As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''lblSelectPaymentProcessor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectPaymentProcessor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''valProcessor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valProcessor As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lstProcessors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstProcessors As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''cmdSubscribe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSubscribe As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblNoPlans control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoPlans As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
