'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Ventrian.SubscriptionTools

    Partial Public Class SignupViewOptions

        '''<summary>
        '''rptBreadCrumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptBreadCrumbs As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''dshSubscriptionSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSubscriptionSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblSubscriptionSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblSubscriptionSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblSubscriptionSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubscriptionSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plAllowMultiSubscriptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAllowMultiSubscriptions As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowMultipleSubscriptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowMultipleSubscriptions As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshPaymentSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshPaymentSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblPaymentSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPaymentSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plPaymentSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPaymentSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plUseLiveProcessor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUseLiveProcessor As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkUseLiveProcessor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseLiveProcessor As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plProcessorUserID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plProcessorUserID As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtProcessorUserID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProcessorUserID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCurrency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCurrency As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''drpCurrency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drpCurrency As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plRequireShippingAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRequireShippingAddress As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkRequireShippingAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRequireShippingAddress As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshContentSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshContentSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblContentSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblContentSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plContentSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plContentSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIntro As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIntro As Global.DotNetNuke.UI.UserControls.TextEditor

        '''<summary>
        '''dshInvoiceSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshInvoiceSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblInvoiceSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblInvoiceSettings As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblInvoiceSettingsHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceSettingsHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plSendInvoice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSendInvoice As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSendInvoice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSendInvoice As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plInvoice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plInvoice As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtInvoice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInvoice As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dshInvoiceTokens control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshInvoiceTokens As Global.DotNetNuke.UI.UserControls.SectionHeadControl

        '''<summary>
        '''tblInvoiceTokens control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblInvoiceTokens As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''lblInvoiceTokensHelp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceTokensHelp As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCity As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCountry As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDisplayName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisplayName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblExpiryDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpiryDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFirstName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFullName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFullName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLastName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPortalName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPortalName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPostalCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostalCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblQty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblQty As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReceiptID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReceiptID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRegion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRegion As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStreet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStreet As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubscriptionDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubscriptionDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubscriptionName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubscriptionName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubscriptionPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubscriptionPrice As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblUsername control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUsername As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
